language: c

sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - genisoimage

before_install:
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal --skip-ghc-check setup

script:
  - stack --no-terminal --skip-ghc-check build --flag b9:-IntegrationTests
  - stack --no-terminal --skip-ghc-check test --flag b9:-IntegrationTests
  - stack --no-terminal --skip-ghc-check haddock --flag b9:-IntegrationTests
  - stack --no-terminal --skip-ghc-check sdist --flag b9:-IntegrationTests

cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.stack-work-cache
  apt: true
