language: nix
script: nix-build release.nix

cache:
  directories:
  - $HOME/nix.store


before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f release.nix buildInputs
- nix copy --to file://$HOME/nix.store -f release.nix depsHostHost

  #before_script:
  #  - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
