language: c

sudo: false

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.2 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2

before_install:
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - chmod a+x ~/.local/bin/stack

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - ./travis_long stack --no-terminal --skip-ghc-check test
  - ./travis_long stack --no-terminal --skip-ghc-check haddock
  - ./travis_long stack --no-terminal --skip-ghc-check sdist

cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.stack-work-cache
  apt: true
