language: c

sudo: false

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal setup
  - stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal test
  - stack --no-terminal haddock
  - stack --no-terminal sdist

cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.ghc
  - ~/.cabal
  - ~/.stack-work-cache
